# Generated by Django 5.0.1 on 2024-01-31 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_poster', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=50)),
                ('movie_poster', models.ImageField(upload_to='images')),
                ('dimension', models.CharField(max_length=50)),
                ('about_movie', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Premium_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiere_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=50)),
                ('premiere_poster', models.ImageField(upload_to='images')),
                ('rent_cost', models.IntegerField()),
                ('buy_cost', models.IntegerField()),
                ('about_movie', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('user_image', models.ImageField(default='images/p1.png', upload_to='images')),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('started_at', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('language', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('event_poster', models.ImageField(upload_to='images')),
                ('place', models.CharField(max_length=50, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
        migrations.CreateModel(
            name='Movie_cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role_name', models.CharField(max_length=50)),
                ('cast_image', models.ImageField(upload_to='images')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_prize', models.IntegerField()),
                ('no_of_tickets', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('email', models.EmailField(default='ex@gmail.com', max_length=254)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.location')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.location')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
