# Generated by Django 5.0.1 on 2024-01-31 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.theatre'),
        ),
    ]
