# Generated by Django 5.0.1 on 2024-01-31 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.theatre'),
        ),
    ]
