# Generated by Django 5.0.1 on 2024-02-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='password',
            field=models.CharField(default='123', max_length=10),
        ),
    ]
